version: '3'
services:
  drone-socket:
      build: 
        context: ./drone-socket
        dockerfile: Dockerfile.test       
      ports:
          - "3000:3000"
      depends_on:
          - "redis"
  drone-simulator:
      build: 
        context: ./drone-simulator
        dockerfile: Dockerfile.test
      ports:
          - "3030:3030"
      depends_on:
          - "drone-socket"
          - "redis" 
  drone-web:
      build: 
        context: ./drone-web
        dockerfile: Dockerfile.test     
      ports:
          - "80:80"
      depends_on:
          - "drone-simulator"
          - "redis"                   
  redis:
      image: redis
      ports:
          - "6379"