version: '3'
services:
  drone-socket:
      build: 
        context: ./drone-socket
        dockerfile: Dockerfile.test       
      ports:
          - "3000:3000"
      depends_on:
          - "redis"
  drone-simulator:
      build: 
        context: ./drone-simulator
        dockerfile: Dockerfile.test
      ports:
          - "3030:3030"
      depends_on:
          - "redis"          
  redis:
      image: redis
      ports:
          - "6379"