version: '3'
services:
  drone-socket:
      build: ./drone-socket        
      ports:
          - "3000:3000"
      depends_on:
          - "redis"
  redis:
      image: redis
      ports:
          - "6379"